// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv"
import { defineConfig } from "prisma/config"

dotenv.config({ path: ".env.local" })

export default defineConfig({
  datasource: {
    url: `mysql://${process.env.DATABASE_USER || "root"}:${process.env.DATABASE_PASSWORD || "password"}@${process.env.DATABASE_HOST || "localhost"}:${process.env.DATABASE_PORT || "3306"}/${process.env.DATABASE_NAME || "localine"}`,
  },
  migrations: {
    path: "prisma/migrations",
  },
  schema: "prisma/schema.prisma",
})
