name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Next.js build
        run: npm run build

      - name: Create release archive
        run: |
          rm -rf .next .vscode node_modules README.md
          mkdir release
          tar \
            --exclude=release \
            -czf release/localineapp.tar.gz \
            .

      - name: Create checksum
        run: |
          sha256sum release/localineapp.tar.gz > release/checksum.txt

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          files: |
            release/localineapp.tar.gz
            release/checksum.txt
